#!/usr/bin/env python

from pdb_clone import pdb, bdb, __version__
if bdb._bdb:
    mode = 'with'
else:
    mode = 'without'
print 'pdb-clone %s (%s the _bdb extension module)' % (__version__, mode)
pdb.main()
