#! /usr/bin/env python
"""Update the version after a commit or an update.

Add the following lines to .hg/hgrc:
[hooks]
commit.version = /bin/sh -c "`hg root`/version-hook.py commit clewn/__version__.py"
update.version = /bin/sh -c "`hg root`/version-hook.py update clewn/__version__.py"
"""

import sys
import os
import optparse
import subprocess
import itertools

pgm = os.path.basename(sys.argv[0])

class HookError(Exception):
    """Base class for version-hook exceptions."""

def indent(str, width=4):
    """Indent a set of lines."""
    return '\n'.join([width * ' ' + x.strip() for x in str.split('\n')])

def command(cmd_list):
    """Run a command."""
    out, err = subprocess.Popen(cmd_list,
                                    stdout=subprocess.PIPE,
                                    stderr=subprocess.PIPE).communicate()
    if err:
        raise HookError, err
    return out.strip()

def hook_type(args):
    """Return the hook type."""
    allowed = ('commit', 'update')
    if not args:
        raise optparse.OptionValueError(
                            '%s: missing %s hook type' % (pgm, allowed))
    htype = args[0]
    if htype not in allowed:
        raise optparse.OptionValueError(
                    '%s: "%s" is not a %s hook type' % (pgm, htype, allowed))
    return htype

def fullpath(filename):
    """Return 'filename' full pathname"""
    try:
        rootdir = fullpath.rootdir
    except AttributeError:
        rootdir = fullpath.rootdir = command(['hg', 'root'])
    return os.path.join(rootdir, filename)

def version(args, debug):
    """Return the version."""
    htype = hook_type(args)
    node = parent = os.environ['HG_PARENT1']
    if htype == 'commit':
        node = os.environ['HG_NODE']
    if debug:
        print >> sys.stderr, 'node-parent:', node, parent

    # build a tags map after removing alphanumeric tags
    taglist = command(['hg', 'tags', '--debug']).split()
    it = iter(taglist)
    tagmap = dict(itertools.izip(it, it))
    alphatags = []
    for tag, nodeid in tagmap.iteritems():
        if tag[0].isalpha():
            alphatags.append(tag)
        else:
            tagmap[tag] = nodeid[nodeid.index(':')+1:]
    for tag in alphatags:
        del tagmap[tag]

    # browse the tags in lexical decreasing order
    for tag in sorted(tagmap.keys(), reverse=True):
        nodeid = tagmap[tag]
        if debug:
            print >> sys.stderr, 'tag-nodeid:', tag, nodeid
        if nodeid.find(parent) == 0:
            # update: updating to 'tag'
            if htype == 'update':
                return tag, ''
            # commit: commiting a new 'tag' (running the tag command)
            else:
                newtag = command(['hg', 'diff',
                                    fullpath('.hgtags'), '-c',  'tip'])
                if newtag != '':
                    if debug:
                        print >> sys.stderr, 'newtag:\n', indent(newtag)
                    return tag, ''
                elif debug:
                    print >> sys.stderr, 'newtag: ""'
        ancestor = command(['hg',  'debugancestor',  nodeid, node])
        if debug:
            print >> sys.stderr, 'ancestor-nodeid:', ancestor, nodeid
        if ancestor[ancestor.index(':')+1:] == nodeid:
            return tag, node

    return 'unknown', ''

if __name__ == '__main__':
    if os.environ.get('HG_ERROR') == '1':
        sys.exit(0)

    parser = optparse.OptionParser(usage=
                    'usage: %prog [options] commit | update [filename]\n\n'
                     + globals()['__doc__'])
    parser.add_option('-d', '--debug', action="store_true", default=False,
                        help='print debugging information on stderr')
    options, args = parser.parse_args()

    try:
        tag, changeset = version(args, options.debug)
        if len(args) == 2:
            f = open(fullpath(args[1]), 'w')
            f.write('# this file is autogenerated by %s\n' % pgm)
            f.write('tag = "%s"\n' % tag)
            f.write('changeset = "%s"\n' % changeset)
            f.close()
        else:
            print 'version = %s.%s' % (tag, changeset)
    except (HookError, optparse.OptionValueError), err:
        print >> sys.stderr, err
        sys.exit(1)

